version: '3.9'

services:
  api:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: BIOFOX-Agent
    restart: always
    ports:
      - 3082:3081
    depends_on:
      - mongodb
      - meilisearch
      - rag-api
    networks:
      - biofox-network
    environment:
      - HOST=0.0.0.0
      - PORT=3081
      - MONGO_URI=mongodb://mongodb:27017/BIOFOX
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://rag-api:8000
      - DEBUG_LOGGING=false
    volumes:
      - /home/biofoxdata/.env:/app/.env
      - /home/biofoxdata/images:/app/client/public/images
      - /home/biofoxdata/uploads:/app/uploads
      # - /home/biofoxdata/logs:/app/api/logs

  mongodb:
    image: mongo
    container_name: biofox-mongodb
    restart: always
    networks:
      - biofox-network
    volumes:
      - /home/biofoxdata/data-node:/data/db
    command: mongod --noauth

  meilisearch:
    image: getmeili/meilisearch:v1.12.3
    container_name: biofox-meilisearch
    restart: always
    networks:
      - biofox-network
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt
    volumes:
      - /home/biofoxdata/meili_data_v1.12:/meili_data

  vectordb:
    image: ankane/pgvector:latest
    container_name: vectordb
    restart: always
    networks:
      - biofox-network
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - /home/biofoxdata/pgdata2:/var/lib/postgresql/data

  rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: biofox-rag-api
    restart: always
    depends_on:
      - vectordb
    networks:
      - biofox-network
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=8000
    env_file:
      - /home/biofoxdata/.env

networks:
  biofox-network:
    driver: bridge